from faker_service import generate_fake_details


def generate_personas(gemini_personas):
    """
    Enrich Gemini-generated personas with fake details.

    Args:
        gemini_personas (list): List of personas generated by Gemini.

    Returns:
        list: List of enriched personas.
    """

    if not gemini_personas:
        return []

    enriched_personas = []

    for persona in gemini_personas:
        fake_details = generate_fake_details()

        # Merge Gemini persona with Faker details
        enriched_persona = {**persona, **fake_details}

        enriched_personas.append(enriched_persona)

    return enriched_personas


# Test the function
if __name__ == "__main__":

    sample_personas = [
        {
            "name": "Rahul Sharma",
            "age": 22,
            "occupation": "Student",
            "traits": ["Curious", "Friendly"],
            "goals": ["Stay fit"],
            "pain_points": ["Busy schedule"],
            "behaviour": ["Uses apps daily"]
        },
        {
            "name": "Priya Reddy",
            "age": 28,
            "occupation": "Software Engineer",
            "traits": ["Analytical", "Organized"],
            "goals": ["Learn AI"],
            "pain_points": ["Lack of time"],
            "behaviour": ["Reads tech blogs"]
        }
    ]

    enriched_personas = generate_personas(sample_personas)

    print("\nEnriched Personas:\n")

    for index, persona in enumerate(enriched_personas, start=1):
        print(f"Persona {index}")
        print(persona)
        print("-" * 50)